version: '2'
services:
    mysql-matcha:
        image: mysql
        ports:
            - "33060:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: db_matcha
    php-matcha:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on :
            - mysql-matcha
        links :
            - mysql-matcha:mysql-matcha
        ports:
            - "8080:80"
        volumes:
            - "./src:/var/www/html"